### ISSUE TITLE
Non Music Entries in XML file crash script 

### ISSUE THREAD

**Issue by c0f** [Stampede/itunes-navidrome-migration#1]
Hi thank you for writing these scripts. I'm always on the look out for scripts that allow me to migrate my iTunes library to other applications.

The iTunes Library file can contain information about purchased and cloud items as well as local audio files. I _think_ this is causing itunestoND.py to crash with the following error:

```
  File "itunestoND.py", line 114, in <module>
    song_path = unquote(it_song_entry.find('key', string='Location').next_sibling.text)
AttributeError: 'NoneType' object has no attribute 'next_sibling'
```

For example Movies use the key: `<key>Movie</key><true/>` and do not have a Location key.

Some items such as Podcasts use an iTunes URL such as:

`<key>Location</key><string>https://itunesu-assets.itunes.apple.com/itunes-assets/CobaltPublic7/v4/REMOVEDLONGSTRING</string>`

I'm wondering if the script should only process XML entries where the location is a file:// URL.

Regards.

**Comment by Stampede** [comment]
I only had my itunes database to work with and I had never purchased anything from the itunes store nor used the itunes cloud service, so there was no way for me to test those cases. But what your guess about the cause of the crash makes a lot of sense and is probably right.

I agree that inserting the condition to skip processing if the string does not start with "file://" would do the job. Unfortunately, I don't have a way to test that.

Maybe I will make a branch and if people have problems they can test it. If feedback is positive, I'll merge it back into the main branch.

**Comment by Stampede** [comment]
I only had my own iTunes database to work with and I had never purchased anything from the iTunes store nor used the iTunes cloud service, so there was no way for me to test those cases. But your guess about the cause of the crash makes a lot of sense and is probably right.

I agree that inserting the condition to skip processing if the string does not start with "file://" would do the job. Unfortunately, I don't have a way to test that.

Can you cut & paste some example entries from the `itunes.XML` file that are causing problems? I will try to update the script so other people don't have these problems.

**Comment by c0f** [comment]
No problem. This is an iTunes Music Store Movie:

```
		<dict>
			<key>Track ID</key><integer>22576</integer>
			<key>Size</key><integer>1402142799</integer>
			<key>Total Time</key><integer>5215382</integer>
			<key>Disc Number</key><integer>1</integer>
			<key>Disc Count</key><integer>1</integer>
			<key>Track Number</key><integer>3</integer>
			<key>Track Count</key><integer>3</integer>
			<key>Year</key><integer>2009</integer>
			<key>Date Modified</key><date>2019-02-13T05:21:12Z</date>
			<key>Date Added</key><date>2018-11-01T00:50:23Z</date>
			<key>Play Count</key><integer>1</integer>
			<key>Release Date</key><date>2009-10-23T07:00:00Z</date>
			<key>Artwork Count</key><integer>1</integer>
			<key>Persistent ID</key><string>225F251A270BDAED</string>
			<key>Track Type</key><string>Remote</string>
			<key>Purchased</key><true/>
			<key>Movie</key><true/>
			<key>Has Video</key><true/>
			<key>Name</key><string>Fantastic Mr. Fox</string>
			<key>Artist</key><string>Wes Anderson</string>
			<key>Album</key><string>《歡迎來到布達佩斯大飯店》+《大吉嶺有限公司》 +《超級狐狸先生》電影三組合</string>
			<key>Genre</key><string>Comedy</string>
			<key>Kind</key><string>Purchased MPEG-4 video file</string>
			<key>Sort Name</key><string>Fantastic Mr. Fox</string>
			<key>Sort Album</key><string>《歡迎來到布達佩斯大飯店》+《大吉嶺有限公司》 +《超級狐狸先生》電影三組合</string>
			<key>Sort Artist</key><string>Wes Anderson</string>
			<key>Content Rating</key><string>uk-movie|PG|200|</string>
		</dict>
```

This is a Podcast:

````
		<dict>
			<key>Track ID</key><integer>5432</integer>
			<key>Date Added</key><date>2018-07-18T21:39:33Z</date>
			<key>Persistent ID</key><string>CD926E5D4F281F12</string>
			<key>Track Type</key><string>URL</string>
			<key>Podcast</key><true/>
			<key>Unplayed</key><true/>
			<key>Name</key><string>Introduction to Business Analytics (Spring 2015)</string>
			<key>Album</key><string>Introduction to Business Analytics (Spring 2015)</string>
			<key>Location</key><string>https://itunesu.itunes.apple.com/feed/id956002980</string>
		</dict>
```

I think a general rule could be to ignore any records where:

- There is no location key , or
- The location key is empty, or
- The location key does not include file://

**Comment by Stampede** [comment]
I took a shot at fixing this. It works OK on my computer with your sample data, so I couldn't really test it too well. There is a new branch. LMK if it solves your issue, and thanks!

https://github.com/Stampede/itunes-navidrome-migration/tree/skip-nonlocal-files
