### ISSUE TITLE
Exceptions with play_count and last_played cause rating import to fail

### ISSUE THREAD

**Issue by c0f** [Stampede/itunes-navidrome-migration#2]
Hi, I noticed that the ratings for a large number of my tracks were not being imported into the Navidrome database. I eventually tracked it down to the following code:

```
    try:
        play_count = int(it_song_entry.find('key', string='Play Count').next_sibling.text)
        last_played = it_song_entry.find('key', string='Play Date UTC').next_sibling.text[:-1] # slice off the trailing 'Z'
        last_played = datetime.datetime.strptime(last_played, '%Y-%m-%dT%H:%M:%S') # convert from string to datetime object. Example string: '20>
    except AttributeError: continue
```

When I replaced `except AttributeError: continue` with the following all of my ratings were successfully imported:

```
    except AttributeError:
        play_count = 0
        last_played = datetime.datetime.strptime("1900-01-01 00:00:00",'%Y-%m-%d %H:%M:%S')
```

I think the lack of a play count or last play date in the iTunes XML triggers the exception which then causes update_playstats to fail because it does not have all of the variables populated for these actions:

```
    update_playstats(artists, artist_id, play_count, last_played)
    update_playstats(albums, album_id, play_count, last_played)
    update_playstats(files, song_id, play_count, last_played, rating=song_rating)
```

I'm happy with 1900-01-01 00:00:00 as a default last_played date but this might suit everyone. I don't know how one would insert a null date.

Once again, thank you for these scripts.

**Comment by Stampede** [comment]
> I think the lack of a play count or last play date in the iTunes XML triggers the exception which then causes update_playstats to fail because it does not have all of the variables populated for these actions:

Yes I remember when I wrote that part of the code. My thinking was that for a song to have a rating, it would have to have a play count and "last played" date also. How can you assign a rating if you had never listened to it? So I basically left it like that probably to save time while writing the script and to avoid writing annotations to the ND database that Navidrome would not write for itself.

Again though, this was under the assumption that for a song to have a star rating, itunes would show at least one play count and play date.

**Comment by c0f** [comment]
Hi, I've tested the new version and it looks good to me.

I moved my current database and ran Navidrome to create a new database that didn't contain any ratings.  Then I waited for Navidrome to index all of my files.

Then I shutdown Navidrome and ran the new itunestoND.py with a library file that contained around 11,000 tracks including 19 Movie entries that do not have a Location. This would have caused the old version to crash.

There were no errors and the import did not crash. I copied the updated database to my Navidrome folder and started Navidrome. All of my tracks and ratings were present.

Regards.

**Comment by Stampede** [comment]
Good to hear! Thanks for the feedback and the help diagnosing!

I don't think I changed anything that would have gotten the script to transfer songs without an itunes playcount and play date, though. Did that start working somehow?

**Comment by c0f** [comment]
Hi, ratings for tracks without playcounts and last played dates do not import, they are still skipped.

I'm happy to just add my workaround to the script though. It's easy enough for me to just add this:

    except AttributeError:
        play_count = 0
        last_played = datetime.datetime.strptime("1900-01-01 00:00:00",'%Y-%m-%d %H:%M:%S')

I'm very happy with your script though, I now have a very quick way to synchronise my iTunes ratings with Navidrome.

Regards.

**Comment by Stampede** [comment]
Yup your workaround should be fine. Thanks again for the feedback & help troubleshooting the other issues.
